### ISSUE TITLE
Optional dependencies?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/networkx-feedstock#1]
NetworkX has a number of optional dependencies that may or may not be worth considering including by default (or at least in a comment). There are several listed in their [docs](https://github.com/networkx/networkx/blob/481f3e8e405cafc05c570e8fc5a2a4d531f86121/doc/source/install.rst#requirements). They also appear below.
- NumPy
- SciPy
- Matplotlib
- GraphViz
- PyGraphviz/pydot - Python interface to graphviz
- PyYAML

Also IPython is listed, but it isn't obvious why it would be a requirement. It seems useful for the examples and possibly some development. Otherwise it seems unnecessary to pull it in.

**Comment by h-vetinari** [comment]
These dependencies became non-optional recently, but since that is causing circularity issues (scipy -> pythran -> networkx -> scipy), it's looking like this will be reverted: https://github.com/networkx/networkx/pull/4967

I see that 2.61 was already released with updated dependencies - those packages might even be yanked from PyPI (because scipy 1.7.0 is currently not installable from source: https://github.com/scipy/scipy/issues/14335), so wanted to notify the feedstock maintainers here that this might need some reaction. CC @conda-forge/networkx

**Comment by jarrodmillman** [comment]
Our new default dependencies are just numpy, scipy, pandas, and matplotlib.  The other dependencies are still optional and will remain so.

**Comment by jarrodmillman** [comment]
Adding numpy, scipy, pandas, and matplotlib as hard dependencies created a ton of problems with downstream packages and users.  So they are no longer hard dependencies.  Would you please remove them from the hard dependencies so this package behaves the way it is intended.

Also, we require Python 3.7 or higher for NetworkX 2.6.  The upcoming NetworkX 2.7 release requires Python 3.8 or higher.  NetworkX 2.7 also will have no hard dependencies.

**Comment by h-vetinari** [comment]
>  Would you please remove them from the hard dependencies so this package behaves the way it is intended.

Done in #

We could also consider adding outputs `networkx-default` and `networkx-extra` based on the new optional [packages](https://github.com/networkx/networkx/tree/main/requirements). Maybe something for 2.7...

**Comment by ocefpaf** [comment]
@h-vetinari I don't have a strong opinion and we, conda-forge, never enforced any rule but we usually do: package-core (or base) and package. Where the former is the minimum dependencies and the latter with some or all optional dependencies. I know that this strategy breaks the model from PyPI. The reason for this is b/c most conda users want a package with "more batteries" and use the core/base only when looking for a lightweight approach (like building a docker image).

**Comment by h-vetinari** [comment]
> I know that this strategy breaks the model from PyPI.

Well, the syntax is different, but I wouldn't say that the model per se is broken. I co-maintain many package that transform `package[extra]` (pip) into `package-extra` (conda-forge), and this works pretty much equivalently.

That's the status quo, and I think we should do that for networkx 2.7 at the lastest (or even in #29 already). But regarding the future (resp. dedicated syntax), there's a couple open discussions:
https://github.com/conda/ceps/pull/9
https://github.com/conda/conda/issues/11053
https://github.com/mamba-org/boa/issues/245

**Comment by MridulS** [comment]
optional deps removed in https://github.com/conda-forge/networkx-feedstock/pull/33
