### ISSUE TITLE
NetworkX 2.5.1

### ISSUE THREAD

**Issue by jarrodmillman** [conda-forge/networkx-feedstock#21]
I just released NetworkX 2.5.1:
https://pypi.org/project/networkx/2.5.1/

We depend on https://pypi.org/project/decorator/, which just had a major new release that broke NetworkX 2.5.  The 2.5.1 patch release just ensures users install an older release of decorator.

It would be great, if you could make a new release based on 2.5.1.  Thanks!

**Comment by synapticarbors** [comment]
@jarrodmillman -- I will review and merge a release as soon as the regro-cf-autotick bot submits a PR with the latest release.

**Comment by synapticarbors** [comment]
closed by #22
