### ISSUE TITLE
Dependencies downloaded via index files differ from dependencies shown at anaconda.org

### ISSUE THREAD

**Issue by mrcblt** [conda-forge/networkx-feedstock#48]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

At https://anaconda.org/conda-forge/networkx/files for version 2.7.1 and build pyhd8ed1ab_0 the dependencies of the networkx package are specified as follows:

![image](https://user-images.githubusercontent.com/34354523/220081001-c278155c-c190-4d03-bf87-234bd22eb991.png)

On 17.07.2022 I successfully created an environment containing `networkx=2.7.1=pyhd8ed1ab_0` together with `matplotlib-base=3.3.2=py39h98787fa_1` and exported the final environment as a .yml file.

Today I wanted to create a new environment from this file and got the following error:

`package networkx-2.7.1-pyhd8ed1ab_0 requires matplotlib-base >=3.4`

As the documentation on the page linked above is still correct and shows the `matplotlib-base>=3.3` dependency, the index file provided by https://conda.anaconda.org/conda-forge/noarch/repodata.json appears to be incorrect as it has the following entry for this particular networkx package:

```json
"networkx-2.7.1-pyhd8ed1ab_0.tar.bz2": {
      "build": "pyhd8ed1ab_0",
      "build_number": 0,
      "depends": [
        "matplotlib-base >=3.4",
        "numpy >=1.19",
        "pandas >=1.3",
        "python >=3.8",
        "scipy >=1.8"
      ],
      "license": "BSD-3-Clause",
      "license_family": "BSD",
      "md5": "5dfa0a6029a8eb2f337578e2950a3eaa",
      "name": "networkx",
      "noarch": "python",
      "sha256": "cc8c33002232ea679d812cd2ca7976d3b45b96db21a3aad6b560e758fa72932c",
      "size": 1613458,
      "subdir": "noarch",
      "timestamp": 1646497427068,
      "version": "2.7.1"
    }
```

As you can see, most of the dependencies are different from those listed on anaconda.org, while the version, build, timestamp and hashes are still the same.

How can it be that dependencies for a package with a particular build number and version change subsequently? This makes exported environment specifications non-reproducible, and makes it impossible to ship environment.yml files with developed software if the installation of the environment may fail at some point in the future due to changed dependencies.

Thanks in advance for your help!

### Installed packages

```shell
Not suitable
```

### Environment info

```shell
     active environment : base
    active env location : /home/mrcblt/miniconda3
            shell level : 1
       user config file : /home/mrcblt/.condarc
 populated config files : /home/mrcblt/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.11.0.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
       base environment : /home/mrcblt/miniconda3  (writable)
      conda av data dir : /home/mrcblt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mrcblt/miniconda3/pkgs
                          /home/mrcblt/.conda/pkgs
       envs directories : /home/mrcblt/miniconda3/envs
                          /home/mrcblt/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.11.0 Linux/4.15.0-204-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1005:1006
             netrc file : None
           offline mode : False
```

**Comment by MridulS** [comment]
The build generated by pyhd8ed1ab_0 was wrong! It was broken https://github.com/conda-forge/networkx-feedstock/issues/44, so the repodata was patched by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/373

I'm not a 100% sure where the website is picking up the data to create the information for deps, but the repodata.json is the accurate one.

**Comment by MridulS** [comment]
@mrcblt let me know if the explanation above makes sense. I'll go ahead and close the issue :)

**Comment by mrcblt** [comment]
Yes, that makes perfect sense, thank you for the explanation! It's still a difficult situation in terms of reproducibility, but I don't see any alternative in case of a faulty build.
