### ISSUE TITLE
Checksum mismatch on 2.4-1

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/networkx-feedstock#58]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

Does this build need to be pulled from conda-forge?

### Issue

```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/networkx-2.4-py_1.tar.bz2'.
  download saved to: /home/conda/staged-recipes/build_artifacts/pkg_cache/networkx-2.4-py_1.tar.bz2
  expected sha256: 428834b2948cdbfd0e7af92a475ae3c3fbe49ddf2de2d5439f75d7ba5e3c5170
  actual sha256: 5e6b33c0b7a29aac6550a392025ded497bd8f498e548237ad71ef5cdb1f85cf9
```

### Installed packages

```shell
None; happens during environment creation
```

### Environment info

```shell
N/a
```

**Comment by jakirkham** [comment]
Am not able to reproduce this. Could you please share the steps you used?

**Comment by mfisher87** [comment]
I'm also failing to reproduce this now. Earlier I was able to reproduce by `conda create -n test "networkx 2.4 py_1"`. My best guess is some intermittent infrastructure problem. Thanks for your time attempting to repro!

**Comment by jakirkham** [comment]
No worries. It's good to catch this sort of thing

Sometimes it can be a network error or something off with the local filesystem cache
